console.log("Hello")
console.log(document.body)
console.log(document.body.childNodes)
console.log(document.body.childNodes[0])
console.log(document.body.childNodes[1])
console.log(document.body.childNodes[1].childNodes)
let cont=document.body.childNodes[1]
console.log(cont.lastChild)
console.log(cont.firstElementChild)
console.log(cont.lastElementChild)
console.log(cont.lastElementChild.parentElement)
console.log(cont.lastElementChild.style.backgroundColor="red")
console.log(cont.lastElementChild.style.color="white")

console.log(document.body.firstElementChild)
console.log(document.body.firstElementChild.childNodes)
console.log(document.body.firstElementChild.children)
console.log(document.body.firstElementChild.children[0])
console.log(document.body.firstElementChild.children[1])
console.log(document.body.firstElementChild.children[1].nextElementSibling)
console.log(document.body.firstElementChild.children[4])
console.log(document.body.firstElementChild.children[4].previousElementSibling)
